# Site settings
title: René Mellema
email: rene.mellema@gmail.com
description: "The internet home of René Mellema, containing his projects and a blog"
baseurl: ""
url: "http://rmellema.github.io"
twitter_username: remellema
github_username:  rmellema

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-sitemap
  - jekyll-mentions

defaults:
  -
    scope:
      path: ""
    values:
      author: "René"
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "page"
    values:
      layout: "page"
